### ISSUE TITLE
Add a script/deploy that deploys the docs

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/antora-ui-teak#4]
Currently we have things set up so that pushing to any docs repo deploys to our docs dev site. We should have a quick one line script that deploys the docs to our production docs site.

**Comment by ZeroStride** [comment]
Completed [d8a92f3](https://github.com/GoCarrot/antora-ui-teak/commit/d8a92f30d83d25a711ef7553014f842322902a3e)
